### ISSUE TITLE
Example code formatting is confusing

### ISSUE THREAD

**Issue by jrkirk61** [swc-uiuc/wrangling-genomics#2]
There are certain sections of code throughout the lessons that are meant as examples and aren't supposed to be run. For example:

```
Since we are working with short reads (36nt) we will be using BWA-backtrack. The general usage for BWA-backtrack is:

$ bwa aln ref_genome.fasta input_file.fastq > output_file.sai
{: .language-bash}
```

I found that students get confused by this and will jump ahead and run this code and then ask why it doesn't work. Or they'll get behind and quickly run everything they think they missed, which will often include these example codes. These kinds of sections need to be formatted differently to avoid confusion. Last time I tried changing these sections to plain italicized text. Does anyone have a suggestion for what might be better, as I'm not that familiar with git markdown?

**Comment by maxim-belkin** [comment]
```kramdown
~~~
# do NOT execute
bwa aln ref_genome.fasta input_file.fastq > output_file.sai
~~~
{: .language-bash}
```

**Comment by jrkirk61** [comment]
Thanks!
