### ISSUE TITLE
How to remove "This lesson is being piloted (Beta version)"

### ISSUE THREAD

**Issue by jrkirk61** [swc-uiuc/wrangling-genomics#3]
I see that there is now a blue box at the top of this lesson that says "This lesson is being piloted (Beta version)". Since this is the third time it is being taught, I don't think it is a beta or pilot version anymore. Where can I find this in github to remove it?

**Comment by maxim-belkin** [comment]
You want to change this line here: https://github.com/swc-uiuc/wrangling-genomics/blob/70a485b3a2ca54cef86be8add84d9e61f7662689/_config.yml#L17
